version: "3"
services:
  wordpress:
    #image: wordpress:latest
    build: ./docker/php
    container_name: ${WORDPRESS_CONTAINER_NAME}
    volumes:
      - "$PWD/docker_volumes/web:/var/www/html"
      - "$PWD/docker_volumes/backup:/tmp/backup"
      - "$PWD/docker_volumes/log:/tmp/log"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env

  db:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - "$PWD/docker_volumes/db-data:/var/lib/mysql"
    env_file: .env

volumes:
  db-data:
